version: '3.8'

services:
  backend:
    build: ./backend
    container_name: habitai-backend-service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - JWT_SECRET=compose_secret_key_habitai
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always

  frontend:
    build: ./frontend
    container_name: habitai-frontend-service
    ports:
      - "7000:7000"
    depends_on:
      - backend
    restart: always
